server:
  port: ${SPRING_CLOUD_EUREKA_PORT}

spring:
  application:
    name: eureka-server
  profiles:
    active: prd

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}